#MRNA rosalind

mrna_nr= 1
protein='MMHWWAGQAAKSWCYRWYDCDNGGCMREKSAKPNVCANGNLIEVENTCNVARISGQTAHGYECWDNRQTAKSIAQKYRPHTDATPRSVMDPVGMNAVVALFPYQYGDMLPQKGDLTEIFTSAVERNETPPCRMEMTVEFSFQHPVVNWRMINTKCCFLWPADSNAFWRWIWQMMHMGQWCHTDTAWSAIMHWEANTGMEYIWDNVNDSHCKYFDSGNLYHVTYEIYQMGKWCDRICSRVWAIHLAKSCNLAPMYTCPWAKINQLQDHPKKPTKPNIQNTYQHDHVMIVISYRMFCFLYKMWATLLFMWFKISANKPFKTEHQIARKQMCCADNRTDNVLTNYEVPHTLRLNGTKEEFMKWCDEQYWMIGESLTRYIHPYIQTDYSHGANGIPEWCFEPCMWPLRWPKRNIYHPMRPKQKQDVWTGSDWTLFERPHFWPMCTWDDLWIFDQMYVTNDEMQIEKIVWWWKMYPIIGYWCFCCWKHIKPICWRTKTMMQGFMIVSFPITRCLMELAKGNRYPAMVHHYSWMHPDSNVCKSTDHWPMGADIEMLLVFWMTNKSGQEDIFEHPRCEYPSADPPTNLYQNDKAQVHKYKQEIAMTKHRKHNQLFDYSVCNLLYNWTCAENPMMVANYHCFLKCTPERDDEWGDPGKPYIGLICGATTANAHMLPTSSIVFLCCGYYPCAECGSPYSDFMYGWPRVLCGPGSAPACEIQGGANSWIDVFAMIFVPHWWHVLQCGCNTWKCYEAWPHTAHDPGNANIYCSIEAGHNWTMCPGRYDVNFTAQHLNLSLARARGNQGCQEKIAPEDGGPEHHDIYLNHNLGMDRALETVCLMRQKWYRLFRHHYNQPAAYGIALWQWVGVMGCADLLPWLVEATCRWMAKWNMRHKPIKEDQWLCNVQHVMISCRWRIWAIRVADERSVVVPEHPKKAIPIEEYKCVVFATFGYAGGFFEEQSRVLWVFEESHKDGMGMKFNFELDPHIHFKWGICSMTVMSKARRSL'

RNA_Codons = {
    "GCU": "A", "GCC": "A", "GCA": "A", "GCG": "A",
    "UGU": "C", "UGC": "C",
    "GAU": "D", "GAC": "D",
    "GAA": "E", "GAG": "E",
    "UUU": "F", "UUC": "F",
    "GGU": "G", "GGC": "G", "GGA": "G", "GGG": "G",
    "CAU": "H", "CAC": "H",
    "AUA": "I", "AUU": "I", "AUC": "I",
    "AAA": "K", "AAG": "K",
    "UUA": "L", "UUG": "L", "CUU": "L", "CUC": "L", "CUA": "L", "CUG": "L",
    "AUG": "M",
    "AAU": "N", "AAC": "N",
    "CCU": "P", "CCC": "P", "CCA": "P", "CCG": "P",
    "CAA": "Q", "CAG": "Q",
    "CGU": "R", "CGC": "R", "CGA": "R", "CGG": "R", "AGA": "R", "AGG": "R",
    "UCU": "S", "UCC": "S", "UCA": "S", "UCG": "S", "AGU": "S", "AGC": "S",
    "ACU": "T", "ACC": "T", "ACA": "T", "ACG": "T",
    "GUU": "V", "GUC": "V", "GUA": "V", "GUG": "V",
    "UGG": "W",
    "UAU": "Y", "UAC": "Y",
    "UAA": "STOP", "UAG": "STOP", "UGA": "STOP"}
 

freq = {}

for value in RNA_Codons.values():
    if value in freq:
        freq[value] += 1
    else:
        freq[value] = 1


for i in range(len(protein)):
    mrna_nr *= freq[protein[i]]
mrna_nr *= freq['STOP'] 
mod=mrna_nr % 1000000

print(mod)
