#RVEC Rosalind

dna='ATCGCACGAAATAAGGGGCTATCGTTGGCAACTGACACCCTCCGCGACTTGTGCACCCCGGCATAATTAAATAGGGCCTCGATAACTGTGCCGCAGGGGTAAAGCAGGTCCGGTACGGTCATACAGATCCCTCGTATAAAATAAAACACGCTTGCTGGAATAGGCCCGAGGTGTCATACAGCTGTTTACGAAATCAGCGACTATGAATACGTCCCCGGACTTGATTGGGATTTGTATGATTCTATAGCTCCGAGGACGCCAAGATCCCGAATTTTTCCGCATCTGGTCCACCCGTACCCATGTTCTTATCCCTTTGGGCGACTTTGCTATCACGCTTTCCCCCTCGTCCTTTTGTGGTTCGGGAAGTCTGAGCGTAATTGTTTTATTTGTAAATGTACACCCTTCAAAGCTTGAGGCTTTCCGATGCTAGGCCCCCATCAACTTTCTGCCGCTGCTCTAACCGCATCCCCCGCATGGATCCCCCGGAAACCGCCAATGGTCTGTGAAGTCAACGCTTGCAGCGTCCACGCCTGCCTGCGACTCGGACCACTTCCATAATGAGAGTCTTTGAGCCACGAGATAATTGGAAATCGGGATGAGTCTGTTCAAAACTACAAAAACGAGAGACTCGCGCCGTGTCGTCCCGTGGTAACATTTCCTAGTGACCCATGCCGTGACTCAGGTCTTCGTGTACTGGCAGGAATGCCAATTGTACTCGGGGGTTTACAGAGAGGGGTCTCAACTCATTAAGGCCATTAAAAAATGTTGACTCTTGAGTCAATGCCTTACATATATGATTCACGCCACAGCCCGCGAGGACGGGCGGGAGCGCAA'

complement=''

conversion = {"A" :'T', "C":'G', "G" : 'C', "T" :'A'}


for i in dna:
    complement+=conversion[i]



reverse_complement = ''
for pos in range(len(dna) - 1, -1, -1):
    reverse_complement += conversion[dna[pos]]

print(reverse_complement)

#or 
'''
reverse_complement= complement[::-1]

print(reverse_complement)
'''


